version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
      - ./package.json:/usr/src/app/package.json
      - ./nest-cli.json:/usr/src/app/nest-cli.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./tsconfig.build.json:/usr/src/app/tsconfig.build.json
    environment:
      - NODE_ENV=development
    command: ["pnpm", "start:dev"]
    stdin_open: true
    tty: true
