version: '3.8'

services:
  app:
    container_name: challenge-api-prod
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      NODE_ENV: production
      LOG_LEVEL: info
      LOG_TYPE: pino
      DEBUG_MODE: 'false'
      PORT: 3000
    ports:
      - '3000:3000'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 5s
      retries: 3
